package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"strings"
)

const generatedHeader = "// Code generated by autodi, DO NOT EDIT.\n\n"

// GeneratedFile represents a file to be written.
type GeneratedFile struct {
	Name    string
	Content []byte
}

// CodeGen orchestrates code generation.
type CodeGen struct {
	cfg        *Config
	graph      *Graph
	commands   []*DiscoveredCommand
	moduleRoot string
	imports    *ImportManager

	// injectZero is the zero value of the current entry's primary return type,
	// used in provider error early-returns (Inject returns (T, func(), error)).
	injectZero string
}

// NewCodeGen creates a code generator.
func NewCodeGen(cfg *Config, graph *Graph, commands []*DiscoveredCommand, moduleRoot string) *CodeGen {
	return &CodeGen{
		cfg:        cfg,
		graph:      graph,
		commands:   commands,
		moduleRoot: moduleRoot,
		imports:    NewImportManager(),
	}
}

// Generate produces one gen.go per discovered cmd entry point.
func (cg *CodeGen) Generate() ([]GeneratedFile, error) {
	var files []GeneratedFile
	for _, cmd := range cg.commands {
		f, err := cg.generateGenFile(cmd)
		if err != nil {
			return nil, fmt.Errorf("generate %s: %w", cmd.RelDir, err)
		}
		files = append(files, f)
	}
	return files, nil
}

// generateGenFile builds cmd/<face>/gen.go: package main + imports + func Inject().
func (cg *CodeGen) generateGenFile(cmd *DiscoveredCommand) (GeneratedFile, error) {
	cg.imports.Reset()

	var body bytes.Buffer
	if err := cg.generateInject(&body, cmd); err != nil {
		return GeneratedFile{}, err
	}

	var full bytes.Buffer
	full.WriteString(generatedHeader)
	full.WriteString("package main\n\n")
	full.WriteString(cg.imports.FormatBlock())
	full.WriteString("\n")
	full.Write(body.Bytes())

	name := cmd.RelDir + "/gen.go"
	src, err := format.Source(full.Bytes())
	if err != nil {
		return GeneratedFile{Name: name, Content: full.Bytes()},
			fmt.Errorf("format %s: %w\n--- source ---\n%s", name, err, full.String())
	}
	return GeneratedFile{Name: name, Content: src}, nil
}

// autoCollectParam records an auto-collected slice parameter.
type autoCollectParam struct {
	idx       int
	elemType  string      // element type string (e.g., "github.com/.../seed.Seeder")
	providers []*Provider // collected providers
}

// generateInitFunc generates an init<Cmd> function for a DI command.
func (cg *CodeGen) generateInject(buf *bytes.Buffer, cmd *DiscoveredCommand) error {
	// Determine which types this entry needs (from the assembler's params)
	var neededTypes []string
	var groupParams []struct {
		idx       int
		groupName string
	}
	var autoParams []autoCollectParam

	for i, param := range cmd.Params {
		groupName := cg.matchGroup(param.TypeStr)
		if groupName != "" {
			groupParams = append(groupParams, struct {
				idx       int
				groupName string
			}{i, groupName})
			// Include all group providers' dependencies
			for _, p := range cg.graph.Groups[groupName] {
				for _, dep := range p.Params {
					neededTypes = append(neededTypes, dep.TypeStr)
				}
			}
		} else if strings.HasPrefix(param.TypeStr, "[]") {
			// Auto-collect: scan all providers implementing this interface
			elemType := param.TypeStr[2:]
			autoProviders := cg.graph.AutoCollect(elemType)
			if len(autoProviders) > 0 {
				autoParams = append(autoParams, autoCollectParam{
					idx:       i,
					elemType:  elemType,
					providers: autoProviders,
				})
				for _, p := range autoProviders {
					for _, dep := range p.Params {
						neededTypes = append(neededTypes, dep.TypeStr)
					}
				}
			} else {
				neededTypes = append(neededTypes, param.TypeStr)
			}
		} else {
			neededTypes = append(neededTypes, param.TypeStr)
		}
	}

	// Resolve providers in topological order, deep-auto-collecting []Interface
	// params as we go. This is a FIXPOINT: collecting a slice (e.g. []Route) pulls
	// in new providers (the sub-router handlers → their services), which may
	// themselves have []Interface params (e.g. kservice's []LoadBalancerDriver).
	// We rescan newly-resolved providers until no new auto-collect params appear.
	deepAutoMap := make(map[string][]autoCollectParam) // "pkg.Func" → auto-collected slice params
	scanned := make(map[string]bool)                   // providers already scanned for []iface params
	extraEdges := make(map[string][]string)            // topo edges: consumer return → collected dep
	providers, err := cg.graph.ProvidersForTypes(neededTypes)
	if err != nil {
		return fmt.Errorf("resolve deps for %s: %w", cmd.Name, err)
	}
	for {
		foundNew := false
		for _, p := range providers {
			key := p.PkgPath + "." + p.FuncName
			if scanned[key] {
				continue
			}
			scanned[key] = true
			for i, param := range p.Params {
				if !strings.HasPrefix(param.TypeStr, "[]") {
					continue
				}
				if cg.matchGroup(param.TypeStr) != "" {
					continue
				}
				elemType := param.TypeStr[2:]
				autoProviders := cg.graph.AutoCollect(elemType)
				if len(autoProviders) == 0 {
					continue
				}
				deepAutoMap[key] = append(deepAutoMap[key], autoCollectParam{
					idx:       i,
					elemType:  elemType,
					providers: autoProviders,
				})
				for _, ap := range autoProviders {
					for _, dep := range ap.Params {
						neededTypes = append(neededTypes, dep.TypeStr)
					}
					// Place collected deps before the consuming provider in topo order.
					for _, ret := range p.Returns {
						for _, dep := range ap.Params {
							extraEdges[ret.TypeStr] = append(extraEdges[ret.TypeStr], dep.TypeStr)
						}
					}
				}
				foundNew = true
			}
		}
		if !foundNew {
			break
		}
		providers, err = cg.graph.ProvidersForTypesWithExtraEdges(neededTypes, extraEdges)
		if err != nil {
			return fmt.Errorf("resolve deps for %s (after auto-collect): %w", cmd.Name, err)
		}
	}

	// Build type → local var name mapping
	varMap := make(map[string]string) // typeStr → local var name
	usedVars := make(map[string]bool)

	// Register singleton provider imports up front so local variable names can
	// avoid colliding with import qualifiers that appear later.
	cg.registerProviderImports(providers)

	// Build set of "consumed" types — types actually referenced as params
	consumedTypes := make(map[string]bool)
	for _, p := range providers {
		for _, param := range p.Params {
			consumedTypes[param.TypeStr] = true
			consumedTypes[cg.graph.resolveType(param.TypeStr)] = true
		}
	}
	// Command params are also consumed
	for _, param := range cmd.Params {
		consumedTypes[param.TypeStr] = true
		consumedTypes[cg.graph.resolveType(param.TypeStr)] = true
	}
	// Group provider params are consumed
	for _, gp := range groupParams {
		for _, p := range cg.graph.Groups[gp.groupName] {
			for _, dep := range p.Params {
				consumedTypes[dep.TypeStr] = true
				consumedTypes[cg.graph.resolveType(dep.TypeStr)] = true
			}
		}
	}
	// Auto-collected provider params are consumed (command-level + deep)
	for _, ap := range autoParams {
		for _, p := range ap.providers {
			for _, dep := range p.Params {
				consumedTypes[dep.TypeStr] = true
				consumedTypes[cg.graph.resolveType(dep.TypeStr)] = true
			}
		}
	}
	for _, aps := range deepAutoMap {
		for _, ap := range aps {
			for _, p := range ap.providers {
				for _, dep := range p.Params {
					consumedTypes[dep.TypeStr] = true
					consumedTypes[cg.graph.resolveType(dep.TypeStr)] = true
				}
			}
		}
	}
	// Interface bindings: if an interface is consumed, its concrete type is too
	for ifaceStr, concreteStr := range cg.graph.Bindings {
		if consumedTypes[ifaceStr] {
			consumedTypes[concreteStr] = true
		}
	}

	// Generate function signature
	primaryType := cg.shortType(cmd.PrimaryRet.TypeStr)
	cg.injectZero = zeroValueForType(cmd.PrimaryRet.Type)
	fmt.Fprintf(buf, "// Inject resolves the dependency graph and assembles %s.\n", primaryType)
	fmt.Fprintf(buf, "func Inject() (%s, func(), error) {\n", primaryType)

	hasAnyError := false
	for _, p := range providers {
		if p.HasError {
			hasAnyError = true
			break
		}
	}
	if hasAnyError {
		cg.imports.Add("fmt", "fmt")
	}

	// Generate provider calls in topological order.
	// For providers with []Interface params (deep auto-collect), generate the slice
	// just before calling that provider.
	var closeables []CloseableField
	for _, p := range providers {
		// Check if this provider has deep auto-collected params
		key := p.PkgPath + "." + p.FuncName
		if aps, ok := deepAutoMap[key]; ok {
			for _, ap := range aps {
				cg.registerProviderImports(ap.providers)

				varName := deriveSliceVarName(ap.elemType)
				if cg.imports.IsQualifier(varName) {
					varName = varName + "List"
				}
				if usedVars[varName] {
					varName = varName + "Auto"
				}
				varName = cg.uniqueLocalVar(varName, usedVars)

				ifaceType := cg.shortType(ap.elemType)
				fmt.Fprintf(buf, "\t%s := make([]%s, 0, %d)\n", varName, ifaceType, len(ap.providers))
				if err := cg.writeSliceProviderCalls(buf, varName, ap.elemType, ap.providers, varMap, usedVars); err != nil {
					return err
				}
				buf.WriteString("\n")

				// Register in varMap so the provider call can reference it
				varMap[p.Params[ap.idx].TypeStr] = varName
			}
		}

		cg.writeLocalProviderCall(buf, p, varMap, usedVars, &closeables, consumedTypes)
		buf.WriteString("\n")
	}

	// Write interface bindings
	for ifaceStr, concreteStr := range cg.graph.Bindings {
		if concreteVar, ok := varMap[concreteStr]; ok {
			if _, needed := varMap[ifaceStr]; !needed {
				// Check if this interface type is needed by any group provider or command param
				if cg.isTypeNeeded(ifaceStr, neededTypes, cmd) {
					varMap[ifaceStr] = concreteVar
				}
			}
		}
	}

	// Build group slices
	for _, gp := range groupParams {
		groupName := gp.groupName
		groupProviders := cg.graph.Groups[groupName]
		if len(groupProviders) == 0 {
			continue
		}

		cg.registerProviderImports(groupProviders)

		groupCfg := cg.cfg.Groups[groupName]
		groupVarName := localVarName(GroupFieldName(groupName))
		if cg.imports.IsQualifier(groupVarName) {
			groupVarName = groupVarName + "List"
		}
		if usedVars[groupVarName] {
			groupVarName = groupVarName + "Group"
		}
		groupVarName = cg.uniqueLocalVar(groupVarName, usedVars)

		ifaceType := cg.qualifyType(groupCfg.Interface, "")
		fmt.Fprintf(buf, "\t%s := make([]%s, 0, %d)\n", groupVarName, ifaceType, len(groupProviders))
		if err := cg.writeSliceProviderCalls(buf, groupVarName, groupCfg.Interface, groupProviders, varMap, usedVars); err != nil {
			return err
		}
		buf.WriteString("\n")

		// Register the slice in varMap for the NewCommand call
		varMap[cmd.Params[gp.idx].TypeStr] = groupVarName
	}

	// Build auto-collected slices
	for _, ap := range autoParams {
		cg.registerProviderImports(ap.providers)

		varName := deriveSliceVarName(ap.elemType)
		if cg.imports.IsQualifier(varName) {
			varName = varName + "List"
		}
		if usedVars[varName] {
			varName = varName + "Auto"
		}
		varName = cg.uniqueLocalVar(varName, usedVars)

		ifaceType := cg.shortType(ap.elemType)
		fmt.Fprintf(buf, "\t%s := make([]%s, 0, %d)\n", varName, ifaceType, len(ap.providers))
		if err := cg.writeSliceProviderCalls(buf, varName, ap.elemType, ap.providers, varMap, usedVars); err != nil {
			return err
		}
		buf.WriteString("\n")

		varMap[cmd.Params[ap.idx].TypeStr] = varName
	}

	// Build assembler args (the assembler lives in this package main → no qualifier).
	var args []string
	for _, param := range cmd.Params {
		if varName, ok := varMap[param.TypeStr]; ok {
			args = append(args, varName)
		} else if varName, ok := varMap[cg.graph.resolveType(param.TypeStr)]; ok {
			args = append(args, varName)
		} else {
			args = append(args, "nil /* unresolved: "+toShortTypeName(param.TypeStr)+" */")
		}
	}

	// providerCleanup runs the Close/Shutdown of constructed singletons, newest first.
	buf.WriteString("\tproviderCleanup := func() {\n")
	for i := len(closeables) - 1; i >= 0; i-- {
		cl := closeables[i]
		if cl.HasCtx {
			cg.imports.Add("context", "context")
			fmt.Fprintf(buf, "\t\tif %s != nil {\n\t\t\t%s.%s(context.Background())\n\t\t}\n", cl.VarName, cl.VarName, cl.Method)
		} else {
			fmt.Fprintf(buf, "\t\tif %s != nil {\n\t\t\t%s.%s()\n\t\t}\n", cl.VarName, cl.VarName, cl.Method)
		}
	}
	buf.WriteString("\t}\n")

	zero := zeroValueForType(cmd.PrimaryRet.Type)
	call := fmt.Sprintf("%s(%s)", cmd.FuncName, strings.Join(args, ", "))

	// Call the assembler, normalizing its (T[,func()][,error]) shape to Inject's
	// uniform (T, func(), error) return.
	switch {
	case cmd.HasCleanup && cmd.HasError:
		fmt.Fprintf(buf, "\tprimary, assemblerCleanup, err := %s\n", call)
		fmt.Fprintf(buf, "\tif err != nil {\n\t\tproviderCleanup()\n\t\treturn %s, nil, err\n\t}\n", zero)
		buf.WriteString("\treturn primary, func() {\n\t\tif assemblerCleanup != nil {\n\t\t\tassemblerCleanup()\n\t\t}\n\t\tproviderCleanup()\n\t}, nil\n")
	case cmd.HasCleanup:
		fmt.Fprintf(buf, "\tprimary, assemblerCleanup := %s\n", call)
		buf.WriteString("\treturn primary, func() {\n\t\tif assemblerCleanup != nil {\n\t\t\tassemblerCleanup()\n\t\t}\n\t\tproviderCleanup()\n\t}, nil\n")
	case cmd.HasError:
		fmt.Fprintf(buf, "\tprimary, err := %s\n", call)
		fmt.Fprintf(buf, "\tif err != nil {\n\t\tproviderCleanup()\n\t\treturn %s, nil, err\n\t}\n", zero)
		buf.WriteString("\treturn primary, providerCleanup, nil\n")
	default:
		fmt.Fprintf(buf, "\tprimary := %s\n", call)
		buf.WriteString("\treturn primary, providerCleanup, nil\n")
	}
	buf.WriteString("}\n")

	return nil
}

// writeLocalProviderCall writes a provider call using local variables.
func (cg *CodeGen) writeLocalProviderCall(buf *bytes.Buffer, p *Provider, varMap map[string]string, usedVars map[string]bool, closeables *[]CloseableField, consumedTypes map[string]bool) {
	qualifier := cg.qualifyFunc(p)
	args := cg.buildLocalArgs(p, varMap)

	// Determine local var names for return types
	var lhsNames []string
	for _, ret := range p.Returns {
		// Check if this return type is actually consumed
		isConsumed := consumedTypes[ret.TypeStr]
		if !isConsumed {
			// Also check via bindings
			for ifaceStr := range consumedTypes {
				if cg.graph.resolveType(ifaceStr) == ret.TypeStr {
					isConsumed = true
					break
				}
			}
		}
		// Also check for closeable — we need the var name for cleanup
		hasClose := isNilable(ret.Type) && checkCloseable(ret.Type, "_") != nil

		if !isConsumed && !hasClose {
			lhsNames = append(lhsNames, "_")
			continue
		}

		fieldName := FieldName(ret.TypeStr)
		varName := localVarName(fieldName)
		// Avoid shadowing import qualifiers
		if cg.imports.IsQualifier(varName) {
			varName = varName + "Svc"
		}
		// Ensure uniqueness
		origVarName := varName
		for i := 2; usedVars[varName]; i++ {
			varName = fmt.Sprintf("%s%d", origVarName, i)
		}
		usedVars[varName] = true
		lhsNames = append(lhsNames, varName)
		varMap[ret.TypeStr] = varName

		// Check for closeable
		if isNilable(ret.Type) {
			if cl := checkCloseable(ret.Type, varName); cl != nil {
				*closeables = append(*closeables, CloseableField{
					VarName: varName,
					Method:  cl.Method,
					HasCtx:  cl.HasCtx,
				})
			}
		}
	}

	if p.HasError {
		if len(lhsNames) > 0 {
			fmt.Fprintf(buf, "\t%s, err := %s(%s)\n", strings.Join(lhsNames, ", "), qualifier, strings.Join(args, ", "))
		} else {
			fmt.Fprintf(buf, "\t_, err := %s(%s)\n", qualifier, strings.Join(args, ", "))
		}
		fmt.Fprintf(buf, "\tif err != nil {\n")
		fmt.Fprintf(buf, "\t\treturn %s, nil, fmt.Errorf(\"%s.%s: %%w\", err)\n", cg.injectZero, p.PkgName, p.FuncName)
		fmt.Fprintf(buf, "\t}\n")
	} else {
		if len(lhsNames) > 0 {
			fmt.Fprintf(buf, "\t%s := %s(%s)\n", strings.Join(lhsNames, ", "), qualifier, strings.Join(args, ", "))
		} else {
			fmt.Fprintf(buf, "\t%s(%s)\n", qualifier, strings.Join(args, ", "))
		}
	}
}

// registerProviderImports pre-registers provider packages so local variable name
// generation can avoid import qualifier collisions.
func (cg *CodeGen) registerProviderImports(providers []*Provider) {
	for _, p := range providers {
		_ = cg.qualifyFunc(p)
	}
}

// uniqueLocalVar returns a unique local variable name that does not collide with
// existing locals or import qualifiers.
func (cg *CodeGen) uniqueLocalVar(base string, usedVars map[string]bool) string {
	if base == "" {
		base = "value"
	}

	name := base
	for i := 2; usedVars[name] || cg.imports.IsQualifier(name); i++ {
		name = fmt.Sprintf("%s%d", base, i)
	}
	usedVars[name] = true
	return name
}

// matchingSliceReturnIndexes returns provider return indexes that should be
// added to a []elemTypeStr slice.
func (cg *CodeGen) matchingSliceReturnIndexes(p *Provider, elemTypeStr string) ([]int, error) {
	if len(p.Returns) == 0 {
		return nil, fmt.Errorf("provider %s.%s has no return values", p.PkgName, p.FuncName)
	}

	resolvedElem := cg.graph.resolveConfigType(elemTypeStr)
	iface := cg.graph.findIfaceType(resolvedElem)

	var matches []int
	for i, ret := range p.Returns {
		if ret.TypeStr == resolvedElem || cg.graph.resolveType(ret.TypeStr) == resolvedElem {
			matches = append(matches, i)
			continue
		}
		if iface != nil {
			if cg.graph.cachedImplements(ret.Type, ret.TypeStr, iface, resolvedElem) {
				matches = append(matches, i)
				continue
			}
			if _, isPtr := ret.Type.(*types.Pointer); !isPtr {
				ptrType := types.NewPointer(ret.Type)
				ptrStr := "*" + ret.TypeStr
				if cg.graph.cachedImplements(ptrType, ptrStr, iface, resolvedElem) {
					matches = append(matches, i)
				}
			}
		}
	}

	if len(matches) == 0 {
		return nil, fmt.Errorf("provider %s.%s has no return matching %s", p.PkgName, p.FuncName, toShortTypeName(resolvedElem))
	}
	return matches, nil
}

// writeSliceProviderCalls emits provider calls that append the selected return
// value into the target slice variable.
func (cg *CodeGen) writeSliceProviderCalls(buf *bytes.Buffer, sliceVarName, elemTypeStr string, providers []*Provider, varMap map[string]string, usedVars map[string]bool) error {
	for _, p := range providers {
		matchIdxs, err := cg.matchingSliceReturnIndexes(p, elemTypeStr)
		if err != nil {
			return err
		}

		qualifier := cg.qualifyFunc(p)
		args := cg.buildLocalArgs(p, varMap)

		if len(p.Returns) == 1 && !p.HasError && len(matchIdxs) == 1 && matchIdxs[0] == 0 {
			fmt.Fprintf(buf, "\t%s = append(%s, %s(%s))\n", sliceVarName, sliceVarName, qualifier, strings.Join(args, ", "))
			continue
		}

		selectedVars := make(map[int]string, len(matchIdxs))
		for _, idx := range matchIdxs {
			selectedType := p.Returns[idx].TypeStr
			selectedVar := localVarName(FieldName(selectedType))
			if cg.imports.IsQualifier(selectedVar) {
				selectedVar = selectedVar + "Val"
			}
			selectedVars[idx] = cg.uniqueLocalVar(selectedVar, usedVars)
		}

		lhs := make([]string, 0, len(p.Returns)+1)
		for i := range p.Returns {
			if selectedVar, ok := selectedVars[i]; ok {
				lhs = append(lhs, selectedVar)
				continue
			}
			lhs = append(lhs, "_")
		}

		if p.HasError {
			lhs = append(lhs, "err")
			fmt.Fprintf(buf, "\t%s := %s(%s)\n", strings.Join(lhs, ", "), qualifier, strings.Join(args, ", "))
			fmt.Fprintf(buf, "\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\treturn %s, nil, fmt.Errorf(\"%s.%s: %%w\", err)\n", cg.injectZero, p.PkgName, p.FuncName)
			fmt.Fprintf(buf, "\t}\n")
		} else {
			fmt.Fprintf(buf, "\t%s := %s(%s)\n", strings.Join(lhs, ", "), qualifier, strings.Join(args, ", "))
		}

		for _, idx := range matchIdxs {
			fmt.Fprintf(buf, "\t%s = append(%s, %s)\n", sliceVarName, sliceVarName, selectedVars[idx])
		}
	}

	return nil
}

// buildLocalArgs constructs the argument list for a provider call using local vars.
func (cg *CodeGen) buildLocalArgs(p *Provider, varMap map[string]string) []string {
	var args []string
	for _, param := range p.Params {
		resolved := cg.graph.resolveType(param.TypeStr)
		if varName, ok := varMap[resolved]; ok {
			args = append(args, varName)
		} else if varName, ok := varMap[param.TypeStr]; ok {
			args = append(args, varName)
		} else {
			args = append(args, "nil /* missing: "+toShortTypeName(param.TypeStr)+" */")
		}
	}
	return args
}

// matchGroup checks if a type string matches a group definition.
// Returns the group name, or "" if not a group.
func (cg *CodeGen) matchGroup(typeStr string) string {
	if !strings.HasPrefix(typeStr, "[]") {
		return ""
	}
	elemType := typeStr[2:]

	for groupName, groupCfg := range cg.cfg.Groups {
		groupIfaceFull := cg.graph.resolveConfigType(groupCfg.Interface)
		if elemType == groupIfaceFull {
			return groupName
		}
	}
	return ""
}

// isTypeNeeded checks if a type is needed by the command or its group/auto-collected providers.
func (cg *CodeGen) isTypeNeeded(typeStr string, neededTypes []string, cmd *DiscoveredCommand) bool {
	for _, t := range neededTypes {
		if t == typeStr {
			return true
		}
	}
	// Check group provider params and auto-collected provider params
	for _, param := range cmd.Params {
		groupName := cg.matchGroup(param.TypeStr)
		if groupName != "" {
			for _, p := range cg.graph.Groups[groupName] {
				for _, dep := range p.Params {
					if dep.TypeStr == typeStr {
						return true
					}
				}
			}
		} else if strings.HasPrefix(param.TypeStr, "[]") {
			elemType := param.TypeStr[2:]
			autoProviders := cg.graph.AutoCollect(elemType)
			for _, p := range autoProviders {
				for _, dep := range p.Params {
					if dep.TypeStr == typeStr {
						return true
					}
				}
			}
		}
	}
	return false
}

// qualifyFunc returns the qualified function call like "iam.NewIAM".
func (cg *CodeGen) qualifyFunc(p *Provider) string {
	alias := cg.imports.Add(p.PkgPath, p.PkgName)
	if alias == "" {
		return p.FuncName
	}
	return alias + "." + p.FuncName
}

// qualifyType converts a type string (possibly short config name) into Go source.
func (cg *CodeGen) qualifyType(typeStr, _ string) string {
	resolved := cg.graph.resolveConfigType(typeStr)
	return cg.shortType(resolved)
}

// shortType converts a fully qualified type string to its short form,
// registering imports as needed.
func (cg *CodeGen) shortType(typeStr string) string {
	prefix := ""
	s := typeStr

	if strings.HasPrefix(s, "*") {
		prefix = "*"
		s = s[1:]
	}

	dotIdx := strings.LastIndex(s, ".")
	if dotIdx < 0 {
		return typeStr
	}

	pkgPath := s[:dotIdx]
	typeName := s[dotIdx+1:]

	if !strings.Contains(pkgPath, "/") {
		resolved := cg.graph.resolveConfigType(typeStr)
		if resolved != typeStr {
			return cg.shortType(resolved)
		}
		if fullPkg, ok := cg.graph.pkgNameToPath[pkgPath]; ok {
			pkgPath = fullPkg
		}
	}

	pkgName := pkgShortName(pkgPath)
	qualifier := cg.imports.Add(pkgPath, pkgName)
	return prefix + qualifier + "." + typeName
}
