package main

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

// generateMermaid produces a Mermaid flowchart (TB) that visualises the full DI graph:
//   - Layout: top-to-bottom — leaf/foundation providers at top, commands at bottom.
//   - Arrows point in injection direction: Dependency --> Consumer.
//   - Providers are clustered in subgraphs by relative package path.
//   - Node labels show the provided type on the first line and constructor name on the second.
//   - Leaf providers (no params) are green; composed providers are blue; invoke are purple.
//   - Commands are grouped in a "Commands" subgraph (dark nodes, stadium shape).
//   - Slice / auto-collected deps use dashed arrows labelled with the slice type (e.g. []Notifier).
//   - Interface-resolved deps use dashed arrows labelled with the interface name.
func generateMermaid(graph *Graph, commands []*DiscoveredCommand, cfg *Config) []byte {
	mg := &mermaidGen{
		graph:    graph,
		commands: commands,
		cfg:      cfg,
		ids:      make(map[string]string),
		usedIDs:  make(map[string]bool),
	}
	return mg.render()
}

type mermaidGen struct {
	graph    *Graph
	commands []*DiscoveredCommand
	cfg      *Config
	ids      map[string]string // providerKey → mermaid node ID
	usedIDs  map[string]bool
}

func (mg *mermaidGen) providerKey(p *Provider) string {
	return p.PkgPath + "::" + p.FuncName
}

// nodeID returns the stable Mermaid identifier for a provider, creating one on first use.
func (mg *mermaidGen) nodeID(p *Provider) string {
	key := mg.providerKey(p)
	if id, ok := mg.ids[key]; ok {
		return id
	}
	base := "P_" + sanitizeMermaidID(p.PkgName+"_"+p.FuncName)
	id := base
	for i := 2; mg.usedIDs[id]; i++ {
		id = fmt.Sprintf("%s_%d", base, i)
	}
	mg.ids[key] = id
	mg.usedIDs[id] = true
	return id
}

func (mg *mermaidGen) render() []byte {
	var buf bytes.Buffer

	buf.WriteString("%% Generated by autodi — DO NOT EDIT\n")
	buf.WriteString("flowchart TB\n\n")

	// ── Style classes ─────────────────────────────────────────────────────────
	// leaf    = foundation providers (no params) — green, the roots of the tree
	// provider = composed providers (have deps)  — blue
	// invoke   = invoke-only providers           — purple
	// command  = CLI entry points                — dark
	buf.WriteString("    classDef leaf    fill:#27ae60,stroke:#1e8449,color:#fff\n")
	buf.WriteString("    classDef provider fill:#2980b9,stroke:#1a5276,color:#fff\n")
	buf.WriteString("    classDef invoke  fill:#8e44ad,stroke:#6c3483,color:#fff\n")
	buf.WriteString("    classDef command fill:#2c3e50,stroke:#17202a,color:#fff\n")
	buf.WriteString("\n")

	// ── Provider subgraphs: one per package ───────────────────────────────────
	pkgMap := make(map[string][]*Provider)
	for _, p := range mg.graph.Providers {
		pkgMap[p.PkgPath] = append(pkgMap[p.PkgPath], p)
	}
	pkgPaths := make([]string, 0, len(pkgMap))
	for pp := range pkgMap {
		pkgPaths = append(pkgPaths, pp)
	}
	sort.Strings(pkgPaths)

	buf.WriteString("    %% ── Providers ────────────────────────────────────────────────────────\n")
	for _, pkgPath := range pkgPaths {
		providers := pkgMap[pkgPath]
		rel := mermaidRelPkg(pkgPath, mg.cfg.Module)
		subID := "sg_" + sanitizeMermaidID(rel)
		fmt.Fprintf(&buf, "    subgraph %s[\"%s\"]\n", subID, rel)
		for _, p := range providers {
			id := mg.nodeID(p)
			label := mg.providerLabel(p)
			if p.IsInvoke {
				fmt.Fprintf(&buf, "        %s[[\"%s\"]]\n", id, label)
			} else {
				fmt.Fprintf(&buf, "        %s[\"%s\"]\n", id, label)
			}
		}
		buf.WriteString("    end\n\n")
	}

	// ── Commands subgraph ─────────────────────────────────────────────────────
	if len(mg.commands) > 0 {
		buf.WriteString("    %% ── Commands ─────────────────────────────────────────────────────────\n")
		buf.WriteString("    subgraph sg_commands[\"Commands\"]\n")
		for _, cmd := range mg.commands {
			cmdID := "C_" + sanitizeMermaidID(cmd.Name)
			fmt.Fprintf(&buf, "        %s([\"⚡ %s\"])\n", cmdID, mg.commandLabel(cmd))
		}
		buf.WriteString("    end\n\n")
		for _, cmd := range mg.commands {
			cmdID := "C_" + sanitizeMermaidID(cmd.Name)
			fmt.Fprintf(&buf, "    class %s command\n", cmdID)
		}
		buf.WriteString("\n")
	}

	// ── Dependency edges: Dependency --> Consumer (injection direction) ────────
	buf.WriteString("    %% ── Dependencies ─────────────────────────────────────────────────────\n")
	for _, p := range mg.graph.Providers {
		mg.writeParamEdges(&buf, mg.nodeID(p), p.Params)
	}
	for _, cmd := range mg.commands {
		cmdID := "C_" + sanitizeMermaidID(cmd.Name)
		mg.writeParamEdges(&buf, cmdID, cmd.Params)
	}
	buf.WriteString("\n")

	// ── Class assignments for providers ──────────────────────────────────────
	buf.WriteString("    %% ── Styles ──────────────────────────────────────────────────────────\n")
	for _, p := range mg.graph.Providers {
		id := mg.nodeID(p)
		switch {
		case p.IsInvoke:
			fmt.Fprintf(&buf, "    class %s invoke\n", id)
		case len(p.Params) == 0:
			fmt.Fprintf(&buf, "    class %s leaf\n", id)
		default:
			fmt.Fprintf(&buf, "    class %s provider\n", id)
		}
	}

	return buf.Bytes()
}

// writeParamEdges emits Mermaid edges in injection direction: Dependency --> Consumer.
//   - Regular deps:           Dep --> Consumer
//   - Interface-resolved deps: Dep -..->|"IfaceName"| Consumer
//   - Slice / group deps:     Impl -.->|"[]ElemType"| Consumer  (dashed, labelled)
func (mg *mermaidGen) writeParamEdges(buf *bytes.Buffer, consumerID string, params []TypeRef) {
	for _, param := range params {
		if strings.HasPrefix(param.TypeStr, "[]") {
			// Slice param — named group or auto-collected
			elemType := param.TypeStr[2:]
			sliceLabel := mermaidEscape("[]" + briefTypeName(elemType))
			if groupName := mg.matchGroupByElem(elemType); groupName != "" {
				for _, gp := range mg.graph.Groups[groupName] {
					fmt.Fprintf(buf, "    %s -.->|\"%s\"| %s\n", mg.nodeID(gp), sliceLabel, consumerID)
				}
				continue
			}
			for _, ap := range mg.graph.AutoCollect(elemType) {
				fmt.Fprintf(buf, "    %s -.->|\"%s\"| %s\n", mg.nodeID(ap), sliceLabel, consumerID)
			}
			continue
		}

		resolved := mg.graph.resolveType(param.TypeStr)
		dep := mg.graph.ProviderMap[resolved]
		if dep == nil {
			dep = mg.graph.ProviderMap[param.TypeStr]
		}
		if dep == nil {
			continue
		}
		depID := mg.nodeID(dep)
		// Dashed arrow when resolved through interface binding
		if param.IsIface && resolved != param.TypeStr {
			shortIface := ifaceShortName(param.TypeStr)
			fmt.Fprintf(buf, "    %s -..->|\"%s\"| %s\n", depID, mermaidEscape(shortIface), consumerID)
		} else {
			fmt.Fprintf(buf, "    %s --> %s\n", depID, consumerID)
		}
	}
}

// matchGroupByElem returns the group name whose interface element type matches elemType.
func (mg *mermaidGen) matchGroupByElem(elemType string) string {
	for groupName, gc := range mg.cfg.Groups {
		if elemType == mg.graph.resolveConfigType(gc.Interface) {
			return groupName
		}
	}
	return ""
}

// providerLabel produces a two-line label: the provided type on the first line,
// the constructor name on the second. Invoke providers show only the function name.
//
//	*user.Service  →  "Service<br/>NewUser"
//	NewRegister    →  "NewRegister"
func (mg *mermaidGen) providerLabel(p *Provider) string {
	if p.IsInvoke || len(p.Returns) == 0 {
		return mermaidEscape(p.FuncName)
	}
	// Pick the first non-error return type as the node identity
	mainType := ""
	for _, ret := range p.Returns {
		if ret.TypeStr != "error" {
			mainType = briefTypeName(ret.TypeStr)
			break
		}
	}
	if mainType == "" {
		return mermaidEscape(p.FuncName)
	}
	// Two-line: "RetType<br/>Constructor"
	return mermaidEscape(mainType) + "<br/>" + mermaidEscape(p.FuncName)
}

// briefTypeName strips the package path and keeps only the bare type name with its
// prefix sigils intact. Examples:
//
//	"*example.com/foo/bar.Baz"       → "*Baz"
//	"[]example.com/foo/bar.Notifier" → "[]Notifier"
//	"string"                          → "string"
func briefTypeName(typeStr string) string {
	if strings.HasPrefix(typeStr, "[]") {
		return "[]" + briefTypeName(typeStr[2:])
	}
	prefix := ""
	s := typeStr
	if strings.HasPrefix(s, "*") {
		prefix = "*"
		s = s[1:]
	}
	if dot := strings.LastIndex(s, "."); dot >= 0 {
		return prefix + s[dot+1:]
	}
	return prefix + s
}

// commandLabel produces a two-line label for a command node:
// first line is the command name, second line lists handler methods.
func (mg *mermaidGen) commandLabel(cmd *DiscoveredCommand) string {
	name := mermaidEscape(cmd.Name)
	var methods []string
	for _, h := range cmd.Handlers {
		methods = append(methods, h.MethodName)
	}
	if len(methods) > 0 && len(methods) <= 4 {
		return name + "<br/>" + mermaidEscape(strings.Join(methods, " | "))
	}
	return name
}

// sanitizeMermaidID converts an arbitrary string to a valid Mermaid node identifier
// by replacing every non-alphanumeric character with an underscore.
func sanitizeMermaidID(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// mermaidRelPkg returns the relative package path within the module,
// or the short package name for external packages.
func mermaidRelPkg(pkgPath, module string) string {
	rel := strings.TrimPrefix(pkgPath, module+"/")
	if rel == pkgPath {
		return pkgShortName(pkgPath) // external dep
	}
	return rel
}

// ifaceShortName extracts just the type name from a full interface type string.
// "*github.com/.../iam.AuthN" → "AuthN"
func ifaceShortName(typeStr string) string {
	short := toShortTypeName(typeStr)
	if dot := strings.LastIndex(short, "."); dot >= 0 {
		return short[dot+1:]
	}
	return short
}

// mermaidEscape replaces characters that break Mermaid label parsing.
func mermaidEscape(s string) string {
	s = strings.ReplaceAll(s, "\"", "#quot;")
	return s
}
