// Code generated by autodi, DO NOT EDIT.

package main

import (
	apicmd "example.com/testapp/cmd/api"
	workercmd "example.com/testapp/cmd/worker"
	"example.com/testapp/internal/cache"
	"example.com/testapp/internal/config"
	"example.com/testapp/internal/db"
	"example.com/testapp/internal/mailer"
	"example.com/testapp/internal/notify"
	"example.com/testapp/internal/notify/email"
	"example.com/testapp/internal/notify/slack"
	"example.com/testapp/internal/orm"
	"example.com/testapp/internal/user"
	"github.com/spf13/cobra"
	"os"
	"strings"
)

func main() {
	root := &cobra.Command{Use: "testapp", Short: "Test Application", Long: "A demo app that showcases autodi dependency injection"}

	type initFunc func(cmd, top *cobra.Command) (func(), error)
	initFuncs := make(map[*cobra.Command]initFunc)

	{
		stub := apicmd.NewAPI(nil, nil)
		tree := stub.Command()
		wireRunE(tree, "create", stub.Create)
		wireRunE(tree, "list", stub.List)
		root.AddCommand(tree)
		initFuncs[tree] = initAPI
	}
	{
		stub := workercmd.NewWorker(nil)
		cmd := stub.Command()
		cmd.RunE = func(c *cobra.Command, _ []string) error { return stub.Handle(c) }
		root.AddCommand(cmd)
		initFuncs[cmd] = initWorker
	}

	var cleanup func()
	root.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		top := cmd
		for top.HasParent() && top.Parent().HasParent() {
			top = top.Parent()
		}
		if fn, ok := initFuncs[top]; ok {
			var err error
			cleanup, err = fn(cmd, top)
			return err
		}
		return nil
	}
	root.PersistentPostRunE = func(cmd *cobra.Command, args []string) error {
		if cleanup != nil {
			cleanup()
		}
		return nil
	}

	if err := root.Execute(); err != nil {
		os.Exit(1)
	}
}

func initAPI(cmd, top *cobra.Command) (func(), error) {
	configSvc := config.NewConfig()

	entClient := orm.NewORM(configSvc)

	cacheSvc := cache.NewCache(configSvc)

	dbSvc := db.NewDB(configSvc)

	notifiers := []notify.Notifier{
		email.NewEmail(configSvc),
		slack.NewSlack(configSvc),
	}

	mailerSvc := mailer.NewMailer(notifiers)

	userService := user.NewUser(dbSvc, cacheSvc, entClient)

	real := apicmd.NewAPI(userService, mailerSvc)
	tree := real.Command()
	wireRunE(tree, "create", real.Create)
	wireRunE(tree, "list", real.List)
	swapRunE(cmd, top, tree)

	return func() {
		if dbSvc != nil {
			dbSvc.Close()
		}
		if cacheSvc != nil {
			cacheSvc.Close()
		}
		if entClient != nil {
			entClient.Close()
		}
	}, nil
}

func initWorker(cmd, top *cobra.Command) (func(), error) {
	configSvc := config.NewConfig()

	notifiers := []notify.Notifier{
		email.NewEmail(configSvc),
		slack.NewSlack(configSvc),
	}

	mailerSvc := mailer.NewMailer(notifiers)

	real := workercmd.NewWorker(mailerSvc)
	realCmd := real.Command()
	realCmd.RunE = func(c *cobra.Command, _ []string) error { return real.Handle(c) }
	swapRunE(cmd, top, realCmd)

	return nil, nil
}

// wireRunE connects a handler method to a subcommand's RunE by kebab-case name.
// For nested commands, the name segments form a path (e.g. "pool-list" matches pool→list).
func wireRunE(parent *cobra.Command, name string, handler func(*cobra.Command) error) {
	// Try exact match first (direct child)
	for _, sub := range parent.Commands() {
		if sub.Name() == name {
			h := handler
			sub.RunE = func(cmd *cobra.Command, _ []string) error { return h(cmd) }
			return
		}
	}
	// Try path-based match: split name by "-" and greedily match child commands
	parts := strings.Split(name, "-")
	wireRunEPath(parent, parts, handler)
}

func wireRunEPath(parent *cobra.Command, parts []string, handler func(*cobra.Command) error) bool {
	if len(parts) == 0 {
		return false
	}
	// Try progressively longer prefixes as the child command name
	for i := 1; i <= len(parts); i++ {
		candidate := strings.Join(parts[:i], "-")
		for _, sub := range parent.Commands() {
			if sub.Name() != candidate {
				continue
			}
			if i == len(parts) {
				// Leaf match
				h := handler
				sub.RunE = func(cmd *cobra.Command, _ []string) error { return h(cmd) }
				return true
			}
			// Try remaining parts as deeper path
			if wireRunEPath(sub, parts[i:], handler) {
				return true
			}
		}
	}
	return false
}

// swapRunE replaces the executing command's RunE with the real one from the DI-built tree.
func swapRunE(executing, stubTop, realTop *cobra.Command) {
	path := relativePath(executing, stubTop)
	target := realTop
	for _, name := range path {
		for _, sub := range target.Commands() {
			if sub.Name() == name {
				target = sub
				break
			}
		}
	}
	executing.RunE = target.RunE
}

func relativePath(cmd, ancestor *cobra.Command) []string {
	if cmd == ancestor {
		return nil
	}
	return append(relativePath(cmd.Parent(), ancestor), cmd.Name())
}
